spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/shop_spring
        username: admin
        password: admin
    liquibase:
        change-log: classpath:db/changelog/db/changelog/changelog-master.xml
